/* tvr1.h - TVrender protocol version 1 */

#ifndef IO_TVR1_H
#define IO_TVR1_H 1

#include "tvr_internal.h"

/* Opcodes */

constexpr uint32_t tvr1_opcodes[] = {
	TVR_INT_OPC_SET_VERSION,
	TVR_INT_OPC_VERTEX_BUFFER_CREATE,
	TVR_INT_OPC_VERTEX_BUFFER_DESTROY,
	TVR_INT_OPC_INDEX_BUFFER_CREATE,
	TVR_INT_OPC_INDEX_BUFFER_DESTROY,
	TVR_INT_OPC_MESH_CREATE,
	TVR_INT_OPC_MESH_BIND_MAT,
	TVR_INT_OPC_MESH_SET_LOC,
	TVR_INT_OPC_MESH_SET_ROT,
	TVR_INT_OPC_MESH_SET_SCALE,
	TVR_INT_OPC_MESH_DESTROY,
	TVR_INT_OPC_TEXTURE_CREATE,
	TVR_INT_OPC_TEXTURE_DESTROY,
	TVR_INT_OPC_MATERIAL_CREATE,
	TVR_INT_OPC_MATERIAL_BIND_TEXTURE,
	TVR_INT_OPC_MATERIAL_DESTROY,
	TVR_INT_OPC_POV_SET_LOC,
	TVR_INT_OPC_POV_SET_ROT,
	TVR_INT_OPC_POV_SET_FOV
};
constexpr unsigned int tvr1_opcode_count = 19;

#endif

